# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49ee9e4788e48e30a42bd78a1b40c376ada6b5d0feb3b6620ac636201caa35c0d25316ace7206fbfe40a4eceb8fb72a9e42bfc9701c83ea1b19bb80c82e446e5

test:
  secret_key_base: 4182093aa96bc9a25590cdf180d6b841bb4b786b040e058c9f81fdf9f9752eec393c66461c653b37aff4c2b7a9237b3655ec472b2ee3b108da11b55811f1b489

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
